version: 2
jobs:
  php_codesniff:
    docker:
      - image: circleci/php:7.4-fpm

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist --no-scripts

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run: ./vendor/bin/phpcs --standard=psr12 src/

  php_tests:
    docker:
      - image: circleci/php:7.4-fpm

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install -y libsqlite3-dev

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist --no-scripts

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run: ./vendor/bin/phpunit

  npm_build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package-lock.json" }}
            - v1-node-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run prod

  push_assets:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package-lock.json" }}
            - v1-node-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run prod

      - run: git config user.email "hello@greenshootlabs.com"
      - run: git config user.name "CI commit"
      - run: git add -f public/* images/*
      - run: git commit -m "Pushing bjuilt assets"
      - run: git push

workflows:
  version: 2
  build:
    jobs:
      - push_assets
